version: 2

jobs:
  build:
    docker:
      - image: docker:17.12.0-ce
    working_directory: ~/cumulus-ecs-task
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          npm install jsonfilter
          docker build -t cumuluss/cumulus-ecs-task .
          docker login -u cumulususer -p $DOCKER_PASSWORD
          ./bin/release.sh

workflows:
  version: 2
  build_release:
    jobs:
      - build
          # filters:
          #   branches:
          #     only: master

